# Generated by Django 2.1.1 on 2018-09-14 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('fathers_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('state', models.CharField(choices=[(None, 'new'), ('S', 'supporter'), ('U', 'undecided'), ('H', 'huldai'), ('Z', 'zamir'), ('A', 'assaf Harel')], max_length=1, null=True, verbose_name='state')),
                ('election_day', models.CharField(choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to voounteer on election day')),
                ('second_ring', models.CharField(choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to be in the second ring')),
                ('home_meetup', models.CharField(choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to host a meetup')),
                ('palrig', models.CharField(choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to hang a palrig')),
                ('digital', models.CharField(choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to  digital volounteer')),
                ('women_rights', models.BooleanField(default=False, verbose_name='Interested in women rights')),
                ('participation', models.BooleanField(default=False, verbose_name='Interested in civic participation')),
                ('commons', models.BooleanField(default=False, verbose_name='Interested in the commons')),
                ('education', models.BooleanField(default=False, verbose_name='Interested in education')),
                ('religion', models.BooleanField(default=False, verbose_name='Interested in religion')),
                ('address', models.TextField(default='', verbose_name='Address')),
                ('notes', models.TextField(default='', verbose_name='Notes')),
                ('zehut', models.CharField(blank=True, max_length=9, null=True, verbose_name='zehut')),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1910, "they can't be more than 108 years old"), django.core.validators.MaxValueValidator(2000, "They can't be younger than 18")], verbose_name='birth year')),
                ('ballot', models.CharField(max_length=30, verbose_name='ballot name')),
            ],
        ),
    ]
