# Generated by Django 2.1.1 on 2018-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denizen',
            name='hood',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('ON', 'Old North')], max_length=2, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='ballot',
            field=models.CharField(blank=True, max_length=30, verbose_name='ballot name'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='digital',
            field=models.CharField(blank=True, choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to  digital volounteer'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='election_day',
            field=models.CharField(blank=True, choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to voounteer on election day'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="father's name"),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='home_meetup',
            field=models.CharField(blank=True, choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to host a meetup'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='name',
            field=models.CharField(max_length=30, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='palrig',
            field=models.CharField(blank=True, choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to hang a palrig'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='second_ring',
            field=models.CharField(blank=True, choices=[(None, 'no thanks'), ('W', 'willing'), ('F', 'fullfilled')], max_length=1, verbose_name='willing to be in the second ring'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'new'), ('S', 'supporter'), ('U', 'undecided'), ('H', 'huldai'), ('Z', 'zamir'), ('A', 'assaf Harel')], max_length=1, null=True, verbose_name='state'),
        ),
    ]
