# Generated by Django 2.1.1 on 2018-09-16 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0003_auto_20180915_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denizen',
            options={'verbose_name': 'תושב', 'verbose_name_plural': 'תושבים'},
        ),
        migrations.AlterField(
            model_name='denizen',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='ballot',
            field=models.CharField(blank=True, max_length=30, verbose_name='שם הקלפי'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1910, 'אין מצב שהיא בת יותר מ 108'), django.core.validators.MaxValueValidator(2000, 'אין מצב שהיא צעירה מ 18')], verbose_name='שמת לידה'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='commons',
            field=models.BooleanField(default=False, verbose_name='מתעניינת במרחב הציבורי'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='digital',
            field=models.CharField(blank=True, choices=[(None, 'לא צודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לעזור בדיגיטל'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='education',
            field=models.BooleanField(default=False, verbose_name='מתעניינת בחינוך'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='election_day',
            field=models.CharField(blank=True, choices=[(None, 'לא צודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן להתנדב ביום בחירות'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואל'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='שם האב'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='home_meetup',
            field=models.CharField(blank=True, choices=[(None, 'לא צודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לארח מפגש'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='hood',
            field=models.CharField(blank=True, choices=[('בבלי צמרות איילון והצפון החדש', 'בבלי צמרות איילון והצפון החדש'), ('הכרם ונווה צדק', 'הכרם ונווה צדק'), ('הצפון הישן (צפוני ודרומי)', 'הצפון הישן (צפוני ודרומי)'), ('התקווה ודרום מזרח העיר', 'התקווה ודרום מזרח העיר'), ('יד אליהו', 'יד אליהו'), ('יפו', 'יפו'), ('לב העיר', 'לב העיר'), ('מעוז אביב והדר יוסף', 'מעוז אביב והדר יוסף'), ("נאות אפקה א' ו-ב'", "נאות אפקה א' ו-ב'"), ('נווה אביבים וסביבתה ורמת אביב', 'נווה אביבים וסביבתה ורמת אביב'), ('נחלת יצחק בצרון ורמת ישראל', 'נחלת יצחק בצרון ורמת ישראל'), ("עג'מי וגבעת עלייה", "עג'מי וגבעת עלייה"), ('פלורנטין ונווה שאנן', 'פלורנטין ונווה שאנן'), ('צהלה והמשתלה', 'צהלה והמשתלה'), ('צפון חדש - כיכר המדינה והדרומי', 'צפון חדש - כיכר המדינה והדרומי'), ('צפון יפו', 'צפון יפו'), ('צפון מערביות', 'צפון מערביות'), ('רביבים שיכון דן ונווה דן', 'רביבים שיכון דן ונווה דן'), ("רמת אביב ג' ואפקה", "רמת אביב ג' ואפקה"), ('רמת החייל ונווה שרת', 'רמת החייל ונווה שרת'), ('שפירא קרית שלום וסביבתה', 'שפירא קרית שלום וסביבתה'), ('תל ברוך ותל ברוך צפון', 'תל ברוך ותל ברוך צפון')], max_length=32, verbose_name='שכונה'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='palrig',
            field=models.CharField(blank=True, choices=[(None, 'לא צודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לתלות פאלריג'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='participation',
            field=models.BooleanField(default=False, verbose_name='מתעניינת בשיתוף ציבור'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='religion',
            field=models.BooleanField(default=False, verbose_name='מתעניינת בהדתה'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='second_ring',
            field=models.CharField(blank=True, choices=[(None, 'לא צודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכל להיות במעגל השני'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'חדש'), ('S', 'תומכת'), ('U', 'מתלבטת'), ('H', 'חולדאי'), ('Z', 'זמיר'), ('A', 'אסף')], max_length=1, null=True, verbose_name='מצב'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='women_rights',
            field=models.BooleanField(default=False, verbose_name='מתעניינת בזכויות נשים'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='zehut',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ת.ז.'),
        ),
    ]
