# Generated by Django 2.1.1 on 2018-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0004_auto_20180916_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='denizen',
            name='source',
            field=models.CharField(default='גשאשdatabase', max_length=20, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denizen',
            name='address',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='כתובת'),
        ),
    ]
