# Generated by Django 2.1.1 on 2018-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0005_auto_20180916_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='denizen',
            name='call_center',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='willing to be a call center volounteer'),
        ),
        migrations.AddField(
            model_name='denizen',
            name='edu_foundations',
            field=models.CharField(default='', max_length=60, verbose_name='Education Foundations'),
        ),
        migrations.AddField(
            model_name='denizen',
            name='field',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='willing to be a volounteer in the field'),
        ),
        migrations.AddField(
            model_name='denizen',
            name='meetup_guest',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='want to be a guest in a meetup'),
        ),
        migrations.AddField(
            model_name='denizen',
            name='whatever',
            field=models.CharField(default='', max_length=60, verbose_name='Whatever'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='digital',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לעזור בדיגיטל'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='election_day',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן להתנדב ביום בחירות'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='home_meetup',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לארח מפגש'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='palrig',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לתלות פאלריג'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='second_ring',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכל להיות במעגל השני'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='state',
            field=models.CharField(blank=True, choices=[('N', 'חדש'), ('!', 'for zippi'), ('W', 'walk in'), ('S', 'תומכת'), ('U', 'מתלבטת'), ('H', 'חולדאי'), ('Z', 'זמיר'), ('A', 'אסף'), ('O', 'other')], default='N', max_length=1, null=True, verbose_name='מצב'),
        ),
    ]
