# Generated by Django 2.1.1 on 2018-09-22 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0006_auto_20180922_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='denizen',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denizen',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='call_center',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לעזור בטלפונים'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='edu_foundations',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='מוסדות חינוך'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='field',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן להתנדב בשטח'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='meetup_guest',
            field=models.CharField(blank=True, choices=[(None, 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='תישמח להתארח במפגש'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='source',
            field=models.CharField(max_length=20, verbose_name='מקור'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='state',
            field=models.CharField(blank=True, choices=[('N', 'חדש'), ('!', 'לטיפולה של ציפי'), ('P', 'המשך טיפול'), ('W', 'פנה אלינו'), ('S', 'תומכת'), ('U', 'מתלבטת'), ('H', 'חולדאי'), ('Z', 'זמיר'), ('A', 'אסף'), ('O', 'מתנגד בכללי')], default='N', max_length=1, null=True, verbose_name='מצב'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='whatever',
            field=models.CharField(default='', max_length=60, verbose_name='לא ברור'),
        ),
    ]
