# Generated by Django 2.1.1 on 2018-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denizen', '0007_auto_20180922_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denizen',
            name='call_center',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לעזור בטלפונים'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='digital',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לעזור בדיגיטל'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='election_day',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן להתנדב ביום בחירות'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='field',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן להתנדב בשטח'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='home_meetup',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לארח מפגש'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='meetup_guest',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='תישמח להתארח במפגש'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='palrig',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכן לתלות פאלריג'),
        ),
        migrations.AlterField(
            model_name='denizen',
            name='second_ring',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('N', 'לא תודה'), ('W', 'בכיף'), ('F', 'בוצע')], max_length=1, verbose_name='מוכל להיות במעגל השני'),
        ),
    ]
